### ISSUE TITLE
How to unzip pretrained model

### ISSUE THREAD

**Issue by tingchihc** [soloist97/densecap-pytorch#3]
Hi,
I download the trained model `train_all_val_all_bz_2_epoch_10_inject_init.pth.tar`  from one drive. Also, I want to use this to evaluate on my own image with describe.py.

1. Can you tell me how to extract this `train_all_val_all_bz_2_epoch_10_inject_init.pth.tar`? I use `tar -xf` . However, I got error.
2. Can you tell me how to edit parser in the describe.py? I do not know what's the config_json mean. Do that mean I need to generate a json file for my image?

thanks,

**Comment by soloist97** [comment]
Hi, 
1. No need to unzip that file, just `torch. load` it
2. `config_json` is the model configuration, which can be generated by `set_args()` in train.py. And you can find a `config.json` from onedrive link. Also, there is an example about how to do inference in the `vg_dataset_visualization.ipynb`.

```
python describe.py --config_json './model_params/train_all_val_all_bz_2_epoch_10_inject_init/config.json' \
  --model_checkpoint './model_params/train_all_val_all_bz_2_epoch_10_inject_init.pth.tar' \
  --img_path './image_to_describe' \
  --result_dir '.' \
  --batch_size 2 --verbose
```

**Comment by tingchihc** [comment]
thanks for your help. I already fix this issue
